# Generated by Django 3.2 on 2021-04-30 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=80, verbose_name='Название категории (русский)')),
                ('name_uz', models.CharField(max_length=80, verbose_name='Название категории (узбекс)')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=80, verbose_name='Название блюда (русский)')),
                ('name_uz', models.CharField(max_length=80, verbose_name='Название блюда (узбекс)')),
                ('desc_ru', models.TextField(blank=True)),
                ('desc_uz', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('photo', models.ImageField(upload_to='media', verbose_name='Фотография блюда')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_content.category', verbose_name='Категория товара')),
            ],
        ),
    ]
